project:
  type: website

website:
  title: "Jasmine Marzouk"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pyjasmine
    left:
      - listings.json

format:
  html:
    theme: cyborg
    css: styles.css



