project:
  type: website

website:
  title: "Jasmine Marzouk"
  navbar:
    left:
      - about.qmd
      - text: 'Codon Classification Project'
        file: ccp.qmd
      - icon: github
        href: https://github.com/pyjasmine
format:
  html:
    theme: flatly
    css: styles.css



